n_particle: 10000
total_charge:
  units: pC
  value: 10
start:
  type: time
random_type: pseudo
xy_dist:
  file: logo049.jpg
  max_x:
    units: millimeter
    value: 10
  max_y:
    units: millimeter
    value: 10
  min_x:
    units: millimeter
    value: -10
  min_y:
    units: millimeter
    value: -10
  threshold: 0.5
  type: file2d
px_dist:
  sigma_px:
    units: MeV/c
    value: 0.001
  type: gaussian
py_dist:
  sigma_py:
    units: MeV/c
    value: 0.02
  type: gaussian
z_dist:
  avg_z:
    units: mm
    value: 0
  sigma_z:
    units: mm
    value: 2.0
  type: gaussian
pz_dist:
  avg_pz:
    units: MeV/c
    value: 10.0
  sigma_pz:
    units: MeV/c
    value: 0.1
  type: gaussian